version: "3.7"

services:
  backend:
    image: postmodern.alexdaniel.org/freergform-backend:latest
    build:
      context: .
    volumes:
      - /home/freergform/data/freergform/data:/srv/data
      - /home/freergform/data/freergform/logs:/srv/logs
    networks:
      - caddy
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first

      labels:
        caddy: freergform.rgvid.eu, www.freergform.rgvid.eu
        caddy.tls: alex.jakimenko+caddy@gmail.com
        caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    external: true
